#+TITLE: WIP - Aristotl
#+AUTHOR: Ben Sima <bensima@gmail.com>
#+DATE: Sunday, April 5, 2015

An API for philosophy data.
  
*Current Status:* Out of planning and in development.

* Rationale
   
There are many great sources for philosophy papers and readings:
  
- Extremely high quality articles on the [[http://plato.stanford.edu/][Stanford Encyclopedia of
  Philosophy]]
- More high quality articles on the [[http://www.iep.utm.edu][University of Tennessee Martin]]
- [[http://www.jstor.org][JSTOR]] has a ton of papers available, some free, some through
  institutional access.
- [[http://philpapers.org][Philpapers]] has a huge database of contemporary philosophy papers.
- Project Gutenberg has a [[http://www.gutenberg.org/wiki/Philosophy_(Bookshelf][philosophy bookshelf]]
- and many more...

  These are free, academic resources for high-quality philosophy. On
  the other hand, popular culture---[[https://news.ycombinator.com/item?id=8709597][especially Silicon Valley tech
  culture]]---does not seem to value academic philosophy. Certain
  figures have become popular, such as Ayn Rand or Alan Turing, but
  the history of philosophy is much richer than pop culture might
  realize.
  
  How can philosophy become as ubiquitous and accessible as computer
  science? My answer to this question is to make philosophy even more
  accessible, in a medium that is familiar to computer scientists and
  software engineers.
  
  Aristotl will accomplish this by exposing an API first, and later by
  creating a web app that will provide access to all of the data
  wrapped in an easy-to-use GUI. The API will contain endpoints for
  every philosopher, concept, and discipline in philosophy. Each
  endpoint will provide bibliographies of references collected from
  multiple sources, full-text articles where available, and
  recommendations for similar entries (calculated by the Aristotl
  system). This data will be persisted in a database and supplied by
  scraping encyclopedias or pulling from the Philpapers API.

* Contributing
   
I take notes in =.org= files in this repo. I plan features and todos
in Orgmode and sometimes GitHub issues.
   
This is a WIP, but if you would like to get involved, you can
contact me via email or [[https://twitter.com/bensima][twitter]], or just start working on issues. I
generally try to follow [[https://guides.github.com/introduction/flow/][GitHub Flow]].
   
* Financial Support

- I shall always run one instance on my own dime
- other people can contribute instances if more are necessary. (Ideally, it
  would be easy to coordinate these automatically a la a botnet, so people can
  spin up new instances whenever they want.)

Seriously considering using [[https://www.patreon.com/][Patreon]].
